// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA4JRRQXc5w5BWjF8q1y0efWSSRBGGjs2w',
    appId: '1:5999872232:web:47ad3c67054a94a151e15d',
    messagingSenderId: '5999872232',
    projectId: 'mod17-flutter-29158',
    authDomain: 'mod17-flutter-29158.firebaseapp.com',
    storageBucket: 'mod17-flutter-29158.firebasestorage.app',
    measurementId: 'G-PWJF63WV1F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBuQeUNFCKrHrGyo2FAtb5x8imvEr4CIAM',
    appId: '1:5999872232:android:3c1eb8b4222cf68b51e15d',
    messagingSenderId: '5999872232',
    projectId: 'mod17-flutter-29158',
    storageBucket: 'mod17-flutter-29158.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDD7rLyVMIv9ky0ycnC8LG-CLZXR1jXJWs',
    appId: '1:5999872232:ios:456bb8157b256fe851e15d',
    messagingSenderId: '5999872232',
    projectId: 'mod17-flutter-29158',
    storageBucket: 'mod17-flutter-29158.firebasestorage.app',
    iosClientId: '5999872232-815j763dlkfrldj7e2j382547qgaoofb.apps.googleusercontent.com',
    iosBundleId: 'com.example.mod17Flutter',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDD7rLyVMIv9ky0ycnC8LG-CLZXR1jXJWs',
    appId: '1:5999872232:ios:456bb8157b256fe851e15d',
    messagingSenderId: '5999872232',
    projectId: 'mod17-flutter-29158',
    storageBucket: 'mod17-flutter-29158.firebasestorage.app',
    iosClientId: '5999872232-815j763dlkfrldj7e2j382547qgaoofb.apps.googleusercontent.com',
    iosBundleId: 'com.example.mod17Flutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA4JRRQXc5w5BWjF8q1y0efWSSRBGGjs2w',
    appId: '1:5999872232:web:97b20901cc316d7051e15d',
    messagingSenderId: '5999872232',
    projectId: 'mod17-flutter-29158',
    authDomain: 'mod17-flutter-29158.firebaseapp.com',
    storageBucket: 'mod17-flutter-29158.firebasestorage.app',
    measurementId: 'G-61621JHNKK',
  );
}
